# Generated by Django 4.2 on 2024-12-03 23:28

from django.db import migrations, models
import django.db.models.deletion
import main.models.Dish


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('idDish', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.PositiveIntegerField()),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=main.models.Dish.dish_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('dateOrder', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idDish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='main.dish')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='main.order')),
            ],
        ),
    ]
